#!/bin/bash
#PBS -k o
#PBS -l nodes=1:ppn=16,vmem=16gb,walltime=08:00:00

[ $PBS_O_WORKDIR ] && cd $PBS_O_WORKDIR

export SINGULARITYENV_WORKDIR=$(pwd)

## modules
echo "Loading modules"
module load singularity
module load nodejs
module unload python
module load python/2.7.3
module load python/mkl/numpy/1.13
echo "Finished loading modules"

export PYTHONPATH=/N/u/brlife/git/nibabel:$PYTHONPATH

set -e
set -x

#execute app
./run.sh

ret=$?
if [ ! $ret -eq 0 ]; then
	exit $ret
fi

#removing files
rm *.nii.gz -f
rm *.tck
rm -r tractograms_directory -f
rm -r examples_directory* -f
rm kdt -f
rm prototypes.npy -f

echo "Complete"
